In [1]:
import torch

torch.__version__

'2.4.1+cpu'

# 认识tensor
tensor是一个三维向量，比如表示图片的时候，可以第一维度表示color channel，第二维表示length，第三维表示width。

1. scalar 是一个标量
2. vector 是一个向量，行向量或者列向量
3. MATRIX 是一个矩阵，n*m
4. TENSOR 是一个三维向量

In [6]:
# 创建一个scalar标量，也就是常数

scalar = torch.tensor(7)
scalar.ndim, scalar.shape, scalar.item(), scalar

(0, torch.Size([]), 7, tensor(7))

In [7]:
# 创建一个vector向量

vector = torch.tensor([7, 7])
vector.ndim, vector.shape, vector[1].item(), vector

(1, torch.Size([2]), 7, tensor([7, 7]))

In [8]:
# 创建一个MATRIX矩阵

MATRIX = torch.tensor([[7, 7], [7, 7]])
MATRIX.ndim, MATRIX.shape, MATRIX[0][0].item(), MATRIX

(2,
 torch.Size([2, 2]),
 7,
 tensor([[7, 7],
         [7, 7]]))

In [9]:
# 创建一个TENSOR

TENSOR = torch.tensor([[[1, 2], [1, 2]], [[2, 3], [2, 3]], [[3, 4], [3, 4]]])
TENSOR.ndim, TENSOR.shape, TENSOR[0][0][0].item(), TENSOR

(3,
 torch.Size([3, 2, 2]),
 1,
 tensor([[[1, 2],
          [1, 2]],
 
         [[2, 3],
          [2, 3]],
 
         [[3, 4],
          [3, 4]]]))

# 其他创建tensor的方法

1. 随机数，tensor.rand(size=(x,x,x))
2. 全0或全1，tensor.zeros(size=(x,x,x)), tensor.ones(size=(x,x,x))
3. 范围值，tensor.arange(start, end, step)
4. shape_like全0或全1，tensor.zeros_like(input=atensor), tensor.ones_like(input=atensor)

In [10]:
# 创建随机数

random_tensor = torch.rand(size = (3, 4))
random_tensor.ndim, random_tensor.shape, random_tensor

(2,
 torch.Size([3, 4]),
 tensor([[0.9623, 0.7569, 0.1766, 0.6042],
         [0.2051, 0.8328, 0.8719, 0.7591],
         [0.7760, 0.1034, 0.3656, 0.2343]]))

In [19]:
# 创建全0或者全1

zeros_tensor = torch.zeros(size=(1, ))
ones_tensor = torch.ones(size=(2, 2))
zeros_tensor, ones_tensor

(tensor([0.]),
 tensor([[1., 1.],
         [1., 1.]]))

In [20]:
# 创建范围值，包含start，不包含end

range_tensor = torch.arange(0, 10, 1)
range_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# 创建shape_like的tensor


zeros_like_tensor = torch.zeros_like(input = range_tensor)
ones_like_tensor = torch.ones_like(input = range_tensor)
range_tensor.shape, range_tensor, zeros_like_tensor.shape, zeros_like_tensor, ones_like_tensor.shape, ones_like_tensor

(torch.Size([10]),
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 torch.Size([10]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 torch.Size([10]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

# tensor的数据类型

tensor的数据类型：https://pytorch.org/docs/stable/tensors.html#data-types
cpu和gpu不大相同

通用的类型有：torch.float32/torch.float, torch.float16/torch.half, torch.float64/torch.double

In [25]:
# tensor，可以得到的重要信息是shape，datatype(default是torch.float32)，device(default是cpu)

float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device, float_16_tensor.shape, float_16_tensor.dtype, float_16_tensor.device

(torch.Size([3]),
 torch.float32,
 device(type='cpu'),
 torch.Size([3]),
 torch.float16,
 device(type='cpu'))

# 操作tensor

1. 加、减、乘、除（均是element-wise）
2. 矩阵相乘
3. 最小、最大、平均、求和（聚合函数）
4. 最小、最大的下标
5. "redtype"、"reshape"
6. getor、setor

In [34]:
# 1.1 加、减、乘、除一个常数
# torch.add(tensor, 10), torch.sub(tensor, 10), torch.mul(tensor, 10), torch.div(tensor, 10), torch.floor_divide(tensor, 10)

tensor = torch.tensor([1, 2, 3, 4])
print(f"tensor: {tensor}")
print(f"tensor + 10: {(tensor + 10, torch.add(tensor, 10))}")
print(f"tensor - 10: {(tensor - 10, torch.sub(tensor, 10))}")
print(f"tensor * 10: {(tensor * 10, torch.mul(tensor, 10))}")
print(f"tensor / 10: {(tensor / 10, torch.div(tensor, 10))}")
print(f"tensor // 10: {(tensor // 10, torch.floor_divide(tensor, 10))}")

tensor: tensor([1, 2, 3, 4])
tensor + 10: (tensor([11, 12, 13, 14]), tensor([11, 12, 13, 14]))
tensor - 10: (tensor([-9, -8, -7, -6]), tensor([-9, -8, -7, -6]))
tensor * 10: (tensor([10, 20, 30, 40]), tensor([10, 20, 30, 40]))
tensor / 10: (tensor([0.1000, 0.2000, 0.3000, 0.4000]), tensor([0.1000, 0.2000, 0.3000, 0.4000]))
tensor // 10: (tensor([0, 0, 0, 0]), tensor([0, 0, 0, 0]))


In [29]:
# 1.2 加、减、乘、除相同shape的tensor
# 同理，也可以使用torch.fun()

tensor1 = torch.tensor([1,2,3,4])
tensor2 = torch.tensor([10,20,30,40])
print(f"tensor1 + tensor2: {tensor1 + tensor2}")
print(f"tensor1 - tensor2: {tensor1 - tensor2}")
print(f"tensor1 * tensor2: {tensor1 * tensor2}")
print(f"tensor1 / tensor2: {tensor1 / tensor2}")
print(f"tensor1 // tensor2: {tensor1 // tensor2}")

tensor1 + tensor2: tensor([11, 22, 33, 44])
tensor1 - tensor2: tensor([ -9, -18, -27, -36])
tensor1 * tensor2: tensor([ 10,  40,  90, 160])
tensor1 / tensor2: tensor([0.1000, 0.1000, 0.1000, 0.1000])
tensor1 // tensor2: tensor([0, 0, 0, 0])


In [50]:
# 2 矩阵相乘

# 标量无法使用矩阵乘法
# scalar1 = torch.tensor(7)
# scalar2 = torch.tensor(8)
# print(f"scalar1 @ scalar2: {scalar1 @ scalar2}")

vector1 = torch.tensor([7])
vector2 = torch.tensor([8])
print(f"vector1 @ vector2: {vector1 @ vector2}")

vector3 = torch.tensor([2, 1])
vector4 = torch.tensor([4, 3])
print(f"vector3 @ vector4: {vector3 @ vector4}")
print(f"vector3.T @ vector4: {vector3.T @ vector4}")
print(f"vector3 @ vector4.T: {vector3 @ vector4.T}")

matrix1 = torch.rand(size=(2,2))
matrix2 = torch.ones_like(input=matrix1)
print(f"matrix1: {matrix1}")
print(f"matrix2: {matrix2}")
print(f"matrix1 @ matrix2: {matrix1 @ matrix2}")

vector1 @ vector2: 56
vector3 @ vector4: 11
vector3.T @ vector4: 11
vector3 @ vector4.T: 11
matrix1: tensor([[0.4036, 0.3328],
        [0.3893, 0.6209]])
matrix2: tensor([[1., 1.],
        [1., 1.]])
matrix1 @ matrix2: tensor([[0.7363, 0.7363],
        [1.0103, 1.0103]])


In [52]:
# 3 聚合函数

x = torch.arange(0, 100, 10)
print(f"Minimum: {(x.min(), torch.min(x))}")
print(f"Maximum: {(x.max(), torch.max(x))}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {(x.type(torch.float32).mean(), torch.mean(x.type(torch.float32)))}") # won't work without float datatype
print(f"Sum: {(x.sum(), torch.sum(x))}")

Minimum: (tensor(0), tensor(0))
Maximum: (tensor(90), tensor(90))
Mean: (tensor(45.), tensor(45.))
Sum: (tensor(450), tensor(450))


In [57]:
# 4 最值下标

tensor = torch.tensor([1,2,3,3])
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {(tensor.argmax().item(), torch.argmax(tensor).item())}")
print(f"Index where min value occurs: {(tensor.argmin(), torch.argmin(tensor))}")

Tensor: tensor([1, 2, 3, 3])
Index where max value occurs: (2, 2)
Index where min value occurs: (tensor(0), tensor(0))


In [61]:
# 5.1 "redtype"

tensor = torch.arange(0, 10, 1)
print(f"tensor type is {(tensor, tensor.dtype)}")
tensor = tensor.type(torch.float32)
print(f"tensor type is {(tensor, tensor.dtype)}")

tensor type is (tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)
tensor type is (tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)


In [97]:
# 5.2 reshape

## 使用reshape, 使用view
## view只能使用contiguous array
## reshape还可以使用non-contiguous

x = torch.arange(0, 8, 1).type(torch.float32)
print(f"x: {x, x.shape}")
x_shape = x.reshape((1, 8))
x_view = x.view(2, 4)
print(f"x_shape: {x_shape, x_shape.shape}")
print(f"x_view: {x_view, x_view.shape}")

y = torch.rand(3, 4)
y_t_shape = y.T.reshape(-1, 12)
print(f"y_t_shape: {y_t_shape, y_t_shape.shape}")
# y.T是non-contiguous
# y_t_view = y.T.view(2, 6)
# RuntimeError: view size is not compatible with 
# input tensor's size and stride (at least one dimension spans across two contiguous subspaces). 
# Use .reshape(...) instead.
# print(f"y_t_view: {y_t_view, y_t_view.shape}")

## 使用stack增加相同的向量，分为dim = 0, dime = 1
x_stack_0 = torch.stack([x, x, x, x], dim = 0)
x_stack_1 = torch.stack([x, x, x, x], dim = 1)
print(f"x_stack_0 :{x_stacked_0, x_stacked_0.shape}")
print(f"x_stack_1 :{x_stacked_1, x_stacked_1.shape}")

## 使用squeeze和unsqueeze，挤压（减少）或者不挤压（增加）外层向量
x_squeeze = x_shape.squeeze()
print(f"x_squeeze: {x_squeeze}")
x_unsqueeze = x_shape.unsqueeze(0)
print(f"x_unsqueeze: {x_unsqueeze}")

x: (tensor([0., 1., 2., 3., 4., 5., 6., 7.]), torch.Size([8]))
x_shape: (tensor([[0., 1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 8]))
x_view: (tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]), torch.Size([2, 4]))
y_t_shape: (tensor([[0.5107, 0.5132, 0.0295, 0.7072, 0.6833, 0.0940, 0.5767, 0.7065, 0.8965,
         0.6741, 0.2527, 0.5032]]), torch.Size([1, 12]))
x_stack_0 :(tensor([[100.,   1.,   2.,   3.,   4.,   5.,   6.,   7.],
        [100.,   1.,   2.,   3.,   4.,   5.,   6.,   7.],
        [100.,   1.,   2.,   3.,   4.,   5.,   6.,   7.],
        [100.,   1.,   2.,   3.,   4.,   5.,   6.,   7.]]), torch.Size([4, 8]))
x_stack_1 :(tensor([[100., 100., 100., 100.],
        [  1.,   1.,   1.,   1.],
        [  2.,   2.,   2.,   2.],
        [  3.,   3.,   3.,   3.],
        [  4.,   4.,   4.,   4.],
        [  5.,   5.,   5.,   5.],
        [  6.,   6.,   6.,   6.],
        [  7.,   7.,   7.,   7.]]), torch.Size([8, 4]))
x_squeeze: tensor([0., 1., 2., 3., 4., 5., 6., 7.])
x_unsq